# Generated by Django 5.1.4 on 2026-05-04 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_code', models.CharField(max_length=20, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('student_name', models.CharField(max_length=200)),
                ('course_title', models.CharField(max_length=200)),
                ('instructor_name', models.CharField(max_length=200)),
                ('completion_date', models.DateField()),
                ('course_duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('is_valid', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
            ],
        ),
    ]
